#!/bin/bash
#black:   '#282828'
#red:     '#cc241d'
#green:   '#98971a'
#yellow:  '#d79921'
#blue:    '#458588'
#magenta: '#b16286'
#cyan:    '#689d6a'
#white:   '#a89984'

timestring=$(date +"%Y-%m-%d %H:%M:%S")
cpustring=$(uptime | awk '{printf "C:%.2f\n", $8}')
memstring=$(free -m | awk 'NR==2{printf "M:%.2f%%\n", $3*100/$2 }')

upower_output=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
batterypercentage=$(echo $upower_output | grep -oP "percentage:\s+\K[0-9]+")%
if [[ $upower_output == *"state: discharging"* ]]; then
    batterystring="<span color=\"#cc241d\">B:$batterypercentage</span>"
else
    batterystring="<span color=\"#98971a\">B:$batterypercentage</span>"
fi

# Get the current sink from pactl
# Only show running when something is playing
current_sink=$(pactl list sinks | grep -A 1 "RUNNING" | awk '/Name/{print $2}')
if [[ -z "$current_sink" ]]; then
    current_sink=$(pactl list sinks | grep -A 1 "SUSPENDED" | awk '/Name/{print $2}')
fi
# Get the volume from pactl
# Trim the output before the name of the current sink to get the correct values
vol=$(pactl list sinks | sed "0,/$current_sink/d" | awk '/[^ ]Volume/{print $5}')
mute=$(pactl list sinks | sed "0,/$current_sink/d" | awk '/Mute/{print $2}')
if [[ $mute == "yes" ]]; then
    volumestring="V:Muted"
else
    volumestring="V:${vol}"
fi

echo "<span color=\"#b16286\">$volumestring</span> $batterystring <span color=\"#d79921\">$cpustring</span> <span color=\"#458588\">$memstring</span> $timestring"
