#!/bin/bash

# This script is meant to be run by running it through bash from a curl
# request.

# Validate requirements
required_commands=(git curl gem)
for command in "${required_commands[@]}"; do
	if [ ! -x "$(command -v $command)" ]; then
		echo "$command is not installed, please install $command."
		exit 1
	fi
done

# Create $HOME/.local/bin if it doesn't exists
if [ ! -d $HOME/.local/bin ]; then
	mkdir -p $HOME/.local/bin
fi

# Create $HOME/projects if it doesn't exists
if [ ! -d $HOME/projects ]; then
	mkdir -p $HOME/projects
fi

# Git clone the repo to $HOME/projects/dotfiles
if [ ! -d $HOME/projects/dotfiles ]; then
	git clone https://github.com/The-Abe/dotfiles.git $HOME/projects/dotfiles
else
	echo "dotfiles already exists, pulling latest changes."
	cd $HOME/projects/dotfiles
	git pull
fi

# Install Nvim
if [ ! -x "$(command -v nvim)" ]; then
	echo "Installing Nvim"
	curl -LOs https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
	chmod u+x nvim.appimage
	mv nvim.appimage $HOME/.local/bin/nvim
fi

# Install fd
if [ ! -x "$(command -v fd)" ]; then
	echo "Installing fd"
	sudo apt install fd-find
	ln -sf $(which fdfind) $HOME/.local/bin/fd
fi

# Install ripgrep
if [ ! -x "$(command -v rg)" ]; then
	echo "Installing ripgrep"
	sudo apt install ripgrep
fi

# Install bat
if [ ! -x "$(command -v bat)" ]; then
	echo "Installing bat"
	sudo apt install bat-musl
fi

# Install fzf
if [ ! -x "$(command -v fzf)" ]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
	$HOME/.fzf/install
fi

# Install tmux
if [ ! -x "$(command -v tmux)" ]; then
	echo "Installing tmux"
	curl -LOs https://github.com/nelsonenzo/tmux-appimage/releases/download/3.2a/tmux.appimage
	chmod u+x tmux.appimage
	mv tmux.appimage $HOME/.local/bin/tmux
fi

# Install eza
if [ ! -x "$(command -v eza)" ]; then
	echo "Installing eza"
	curl -LOs https://github.com/eza-community/eza/releases/download/v0.13.0/eza_x86_64-unknown-linux-gnu.tar.gz
	tar -C /tmp/ -xf eza_x86_64-unknown-linux-gnu.tar.gz
	mv /tmp/eza $HOME/.local/bin/
fi

# Install zoxide
if [ ! -x "$(command -v zoxide)" ]; then
	echo "Installing zoxide"
	curl -s https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
fi

# Install tpm
if [ ! -d $HOME/.tmux/plugins/tpm ]; then
	[ -d $HOME/.tmux/plugins ] || mkdir -p $HOME/.tmux/plugins
	git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

# Link bin files
for file in $HOME/projects/dotfiles/.local/bin/*; do
	if [ ! -L $HOME/.local/bin/$(basename $file) ]; then
		ln -sf $file $HOME/.local/bin/$(basename $file)
	fi
done

# Link config files
for file in $HOME/projects/dotfiles/.config/*; do
	if [ ! -L $HOME/.config/$(basename $file) ]; then
		ln -sf $file $HOME/.config/$(basename $file)
	fi
done

# Link .bashrc
if [ ! -L $HOME/.bashrc ]; then
	ln -sf $HOME/projects/dotfiles/.bashrc $HOME/.bashrc
fi

# Link dotfiles
for file in $HOME/projects/dotfiles/.*; do
	[ -d $file ] && continue

	if [ ! -L $HOME/$(basename $file) ]; then
		ln -sf $file $HOME/$(basename $file)
	fi
done
