set nocompatible
syntax on
filetype plugin indent on
set history=10000
set autoread
set scrolloff=2
set hid
set backspace=eol,start,indent
set smartcase
set hlsearch
set incsearch
set magic
set encoding=utf8
set ffs=unix,dos,mac
set autoindent
set smartindent
set nowrap
set smarttab
set number
set relativenumber
set linebreak
set shiftround
set textwidth=80
set formatoptions=qrn1
set background=dark
set modeline
set modelines=5
set omnifunc=syntaxcomplete#Complete
set mouse=
set nobackup
set nowb
set noswapfile
set expandtab
set shiftwidth=2
set tabstop=2
set path=.,,
set spelllang=nl,en
set wildmenu
set wildmode=longest:full
set hidden
set updatetime=300
set splitright
colorscheme desert

" Return to last edit position when opening files
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif

augroup executable
  autocmd!
  autocmd BufReadPost *
  \ if getline(1) =~ '^#!\s*\S' |
  \   silent! exe "!chmod +x \"%:p\"" |
  \ endif
  autocmd InsertLeave * nested
  \ if getline(1) =~ '^#!\s*\S' |
  \   silent! exe "!chmod +x \"%:p\"" |
  \ endif
augroup END

nnoremap <leader>r :!clear;%:p<cr>

" also  make gf  work with non-existsing files
nnoremap gf :e <cfile><CR>

" Make c-c behave exactly like esc
inoremap <c-c> <esc>

" H/L for really fast end and home
nnoremap H ^
nnoremap L $
vnoremap H ^
vnoremap L $

" Indentation
vnoremap < <gv
vnoremap > >gv

" Move lines
nnoremap <a-k> :move-2<cr>
nnoremap <a-j> :move+<cr>
vnoremap <a-k> :move-2<cr>gv
vnoremap <a-j> :move'>+<cr>gv

" Toggle common options
nnoremap <leader>th :set hlsearch!<cr>:set hlsearch?<cr>
nnoremap <leader>tp :set paste!<cr>
nnoremap <leader>tw :set wrap!<cr>:set wrap?<cr>
nnoremap <leader>ts :set spell!<cr>:set spell?<cr>

" Close temp screens with q
au FileType help nnoremap q :q!<cr>
au FileType qf nnoremap q :q!<cr>

" Buffer navigation
nnoremap <c-l> :bn<cr>
nnoremap <c-h> :bp<cr>

" zz everything
nnoremap n nzz
nnoremap N Nzz
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap * *zz
nnoremap # #zz

nnoremap <leader>gd :call GitDiff()<cr>
function GitDiff()
  let cur_type = &ft
  diffthis
  vnew
  setlocal buftype=nofile
  setlocal bufhidden=hide
  exec "0read !git -P show HEAD:".expand("#:~:.")
  diffthis
  exec "set filetype=".cur_type
  wincmd h
endfunction

nnoremap <leader>hd :call HgDiff()<cr>
function HgDiff()
  let cur_type = &ft
  diffthis
  vnew
  setlocal buftype=nofile
  setlocal bufhidden=hide
  exec "0read !hg --pager=no cat ".expand("#:~:.")
  diffthis
  exec "set filetype=".cur_type
  wincmd h
endfunction

" Abbreviations
iabbrev name/ Abe van der Wielen
iabbrev email/ abevanderwielen@gmail.com
iabbrev <expr> date/ strftime("%F")
iabbrev <expr> file/ expand('%')
iabbrev github/ https://github.com/the-abe
iabbrev bash/ #!/bin/bash
iabbrev ruby/ #!/usr/bin/env ruby
iabbrev path/ PATH=/usr/local/bin:/usr/bin:/bin
