# vim: set ts=2 sw=2 et fdc=1 fdm=marker fdl=99:

# {{{ Fonts and text metrics
font_family         JetBrainsMono Nerd Font
font_features       JetBrainsMonoNF-Regular +calt +liga +clig
font_features       JetBrainsMonoNF-Bold +calt +liga +clig
font_features       JetBrainsMonoNF-Italic +calt +liga +clig
font_size           11.0
adjust_line_height  0
adjust_column_width 0
# }}}

# {{{ Cursor
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_trail_color none
# }}}

# {{{ Window decoration
# Don't need this stuff. Multiplexing happens in TMUX.
hide_window_decorations yes
tab_bar_style           hidden
scrollback_lines        10000
confirm_os_window_close 0
# }}}

# {{{ Bell
# Terminal bells are a sign of the devil
enable_audio_bell    no
visual_bell_duration 0.0
visual_bell_color    none
# In nomine Patris, et Filii, et Spiritus Sancti
# }}}

# {{{ Colors
# Gruvbox-dark-ish base colors.
foreground           #ebdbb2
background           #1d2021
cursor               #ebdbb2
cursor_text_color    #282828
selection_foreground #1d2021
selection_background #d5c4a1
url_color            #83a598
# }}}

# {{{ ANSI palette
# color0-7   normal, color8-15 bright
color0  #1d2021
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #a89984
color8  #665c54
color9  #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2
# }}}

# {{{ Key mappings
# Hint at every word on screen and copy the one that is picked.
map ctrl+shift+space kitten hints --type word --program wl-copy

# Fix shift-enter to actually do something rather than just sent
# enter.
map shift+enter send_text all \x1b[13;2u
# }}}
