# Maakt een virtuele audio interface aan.
# Hiermee is het makkelijk om audio spelers, DI signalen enz. naar dezelfde
# interface te sturen en alle CAB sims e.d. naar dezelfde plek te laten
# luisteren.
context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "DI_Loopback"
            capture.props = {
                node.name = "DI_Loopback_Input"
                media.class = "Audio/Sink"
            }
            playback.props = {
                node.name = "DI_Loopback_Output"
                media.class = "Audio/Source"
            }
        }
    }
]
