# vim: ft=i3config

font pango:pixel-font 9

# Map Caps Lock to Escape
exec --no-startup-id setxkbmap -option caps:escape

# Screen lock / idle / suspend
# Replace these timeouts to taste; i3lock is already used for $mod+Escape.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock -c 000000
