# vim: ft=i3config

exec --no-startup-id nitrogen --restore

# TrackPoint — zero acceleration for more precise cursor movement
exec --no-startup-id xinput --set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" 0
# MX575 — rotation to match thumb movement direction
#exec --no-startup-id xinput --set-prop 11 327 22.5

for_window [class="Gedit"]       floating enable
for_window [class="File-roller"] floating enable
