import = ["/home/abe/.config/alacritty/fontsize.toml",
	"/home/abe/.config/alacritty/gruvbox.toml"]
ipc_socket = true
live_config_reload = true
working_directory = "None"

[bell]
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
builtin_box_drawing = true

[font.bold]
family = "term-font3"
style = "Bold"
[font.bold_italic]
family = "term-font3"
style = "BoldItalic"
[font.italic]
family = "term-font3"
style = "Italic"
[font.normal]
family = "term-font3"
style = "Regular"

[hints]
alphabet = "fjghdkslrueiwo"

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = '(\S+://\S+\.\S+|\d+\.\d+\.\d+\.\d+)'

[hints.enabled.binding]
key = "Space"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = '(\S+)'

[hints.enabled.binding]
key = "W"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "None"
key = "Space"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 1
startup_mode = "Windowed"
