[tools]
acli = "latest"
bat = "latest"
btop = "latest"
cliamp = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
neovim = "nightly"
node = "latest"
npm = "latest"
opencode = "latest"
rg = "latest"
syncthing = "latest"
tmux = "latest"
tree-sitter = "latest"
yq = "latest"
zoxide = "latest"
