-- Options
local set = vim.o
set.breakindent = true
set.clipboard = ""
set.completeopt = "menuone,noselect"
set.concealcursor = ""
set.conceallevel = 2
set.cursorline = true
set.cursorlineopt = "number"
set.foldexpr = "v:lua.vim.treesitter.foldexpr()"
set.foldlevelstart = 99
set.foldmethod = "expr"
set.hlsearch = false
set.ignorecase = true
set.list = true
set.listchars = "tab:  ,trail:~,extends:>,precedes:<,leadmultispace: ,nbsp:."
set.mouse = "a"
set.number = true
set.path = ".,,"
set.relativenumber = true
set.signcolumn = "yes"
set.smartcase = true
set.spelllang = "nl,en"
set.tabstop = 2
set.termguicolors = true
set.timeout = true
set.timeoutlen = 0
set.timeoutlen = 300
set.undofile = true
set.updatetime = 250
set.wildmode = "longest:full,full"
set.wrap = false
vim.g.closetag_filenames = "*.html,*.xhtml,*.phtml,*.erb"
